/**
 * LeadScope Niche Website Templates Dataset
 * Ordered according to priority: Wellness & Holistic -> Fitness & Athletics -> Beauty & Personal Care -> Luxury -> Real Estate -> Healthcare -> Automotive -> Services
 */

const TEMPLATES_DATA = [
  // 1. Wellness & Holistic
  {
    id: "wellness_project",
    title: "Holistic Wellness & Lifestyle Coaching",
    folder: "wellness-project",
    category: "wellness",
    categoryLabel: "Wellness & Holistic",
    description: "Calm, organic design framework ideal for holistic health coaches, nutritionists, naturopaths, and wellness retreats.",
    icon: "fa-leaf",
    badge: "Featured Wellness",
    gradient: "linear-gradient(135deg, #84cc16 0%, #4d7c0f 100%)",
    accentColor: "#84cc16",
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80",
    tags: ["Wellness Coach", "Nutritionist", "Naturopathy", "Mindfulness"],
    features: ["Free Consultation", "Health Quiz", "Recipe Journal", "Workshop Enrolment"]
  },
  {
    id: "pranic_healing_2",
    title: "Pranic Energy Healing & Meditation",
    folder: "pranic-healing-2",
    category: "wellness",
    categoryLabel: "Wellness & Holistic",
    description: "Serene, mystical layout designed for energy healers, pranic healing sanctuaries, meditation centers, and holistic spiritual practitioners.",
    icon: "fa-yin-yang",
    badge: "Holistic Energy",
    gradient: "linear-gradient(135deg, #10b981 0%, #047857 100%)",
    accentColor: "#10b981",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
    tags: ["Pranic Healing", "Meditation", "Energy Cleanse", "Chakra Balance"],
    features: ["Session Booking", "Healing Testimonials", "Event Calendar", "Guided Audio"]
  },

  // 2. Fitness & Athletics
  {
    id: "cross_fit",
    title: "CrossFit & High Intensity Gym",
    folder: "Cross Fit",
    category: "fitness",
    categoryLabel: "Fitness & Athletics",
    description: "High-energy, gritty performance theme engineered for CrossFit boxes, functional fitness centers, and strength conditioning gyms.",
    icon: "fa-dumbbell",
    badge: "High Energy",
    gradient: "linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)",
    accentColor: "#ef4444",
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80",
    tags: ["CrossFit", "WOD Tracker", "Strength & Conditioning", "Free Pass"],
    features: ["Class Timetable", "Free Trial Claim", "Coach Profiles", "Transformation Stories"]
  },
  {
    id: "fitness_trainer",
    title: "Personal Fitness Coach & Trainer",
    folder: "fitness trainer",
    category: "fitness",
    categoryLabel: "Fitness & Athletics",
    description: "Personal brand website template tailored for online fitness coaches, 1-on-1 personal trainers, and transformation specialists.",
    icon: "fa-person-running",
    badge: "Personal Brand",
    gradient: "linear-gradient(135deg, #14b8a6 0%, #0f766e 100%)",
    accentColor: "#14b8a6",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80",
    tags: ["Online Coaching", "1-on-1 Training", "Nutrition Plan", "Personal Coach"],
    features: ["Client Transformations", "Program Options", "Calorie Guide", "Discovery Call CTA"]
  },
  {
    id: "gym_website",
    title: "Comprehensive Gym & Fitness Club",
    folder: "gym-website",
    category: "fitness",
    categoryLabel: "Fitness & Athletics",
    description: "Modern, feature-loaded gym membership platform with class schedules, trainer rosters, membership tiers, and facility tour.",
    icon: "fa-heart-pulse",
    badge: "Full Featured",
    gradient: "linear-gradient(135deg, #6366f1 0%, #4338ca 100%)",
    accentColor: "#6366f1",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
    tags: ["Gym Pass", "Fitness Club", "Group Classes", "Weightlifting"],
    features: ["Membership Pricing", "Day Pass Claim", "Virtual Tour", "Class Schedule"]
  },

  // 3. Beauty & Salon
  {
    id: "luxurious_salon_website",
    title: "Luxurious Salon & Hair Atelier",
    folder: "luxurious-salon-website",
    category: "beauty",
    categoryLabel: "Beauty & Personal Care",
    description: "Elegant, editorial-style boutique salon template designed for high-end hair stylists, color specialists, and luxury hair extensions.",
    icon: "fa-scissors",
    badge: "Editorial Style",
    gradient: "linear-gradient(135deg, #f43f5e 0%, #be123c 100%)",
    accentColor: "#f43f5e",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80",
    tags: ["Hair Salon", "Atelier", "Stylist Showcase", "Color Spa"],
    features: ["Stylist Selector", "Service Pricing Menu", "Instagram Feed", "Appointment Form"]
  },
  {
    id: "nail_art",
    title: "Nail Art & Manicure Studio",
    folder: "nail-art",
    category: "beauty",
    categoryLabel: "Beauty & Personal Care",
    description: "Trendy, playful aesthetic showcasing gel extensions, acrylic nail art, custom designs, and luxury spa pedicures.",
    icon: "fa-hand-sparkles",
    badge: "Trending",
    gradient: "linear-gradient(135deg, #a855f7 0%, #7e22ce 100%)",
    accentColor: "#a855f7",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80",
    tags: ["Nail Art", "Acrylics", "Manicure", "Pedicure"],
    features: ["Design Lookbook", "Shape & Length Guide", "Add-On Customizer", "Insta Booking"]
  },

  // 4. Luxury Events & Jewelry
  {
    id: "luxury_yacht_wedding_planners",
    title: "Luxury Yacht Wedding Planners",
    folder: "Luxury Yacht Wedding Planners",
    category: "luxury",
    categoryLabel: "Luxury Events & Weddings",
    description: "Breathtaking nautical luxury design built for elite yacht wedding planners, luxury charters, and high-end event producers.",
    icon: "fa-anchor",
    badge: "Elite Design",
    gradient: "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)",
    accentColor: "#3b82f6",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
    tags: ["Weddings", "Yacht Charter", "Luxury Events", "VIP Concierge"],
    features: ["Fleet Showcase", "Interactive Itinerary", "RSVP Form", "Virtual Consultation"]
  },
  {
    id: "luxury_event_caterers_staffing",
    title: "Luxury Event Catering & Staffing",
    folder: "Luxury Event Caterers & Staffing",
    category: "luxury",
    categoryLabel: "Luxury Events & Weddings",
    description: "Sophisticated culinary portfolio featuring menu showcases, private chef experiences, corporate galas, and professional event staffing.",
    icon: "fa-utensils",
    badge: "High Demand",
    gradient: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
    accentColor: "#f59e0b",
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=800&q=80",
    tags: ["Fine Dining", "Private Chef", "Event Staffing", "Gala Caterer"],
    features: ["Interactive Menus", "Dietary Filters", "Event Calculator", "Booking Calendar"]
  },
  {
    id: "jewelry",
    title: "Fine Jewelry & Luxury Boutique",
    folder: "jewelry",
    category: "luxury",
    categoryLabel: "Luxury Events & Weddings",
    description: "Sophisticated minimalist ecommerce template for bespoke jewelers, custom engagement rings, diamonds, and luxury watch curators.",
    icon: "fa-gem",
    badge: "Minimalist Luxe",
    gradient: "linear-gradient(135deg, #fbbf24 0%, #b45309 100%)",
    accentColor: "#fbbf24",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    tags: ["Fine Jewelry", "Custom Rings", "Diamonds", "Watches"],
    features: ["High-Res Showcase", "Custom Ring Builder", "VIP Appointment", "Care Guide"]
  },

  // 5. Real Estate & Co-Living
  {
    id: "student_pg_accommodation",
    title: "Student PG & Co-Living Hostels",
    folder: "Student PG Accommodation",
    category: "realestate",
    categoryLabel: "Real Estate & Co-Living",
    description: "Vibrant, feature-packed layout for student hostels, PG accommodations, co-living spaces, and furnished room rentals.",
    icon: "fa-building-user",
    badge: "High Booking",
    gradient: "linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)",
    accentColor: "#8b5cf6",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80",
    tags: ["PG Hostel", "Student Living", "Furnished Rooms", "Co-Living"],
    features: ["Virtual Room Tour", "Amenity Checklist", "Rent Calculator", "Visit Request"]
  },

  // 6. Healthcare & MedSpa
  {
    id: "aesthetic_anti_aging_medicine",
    title: "Aesthetic & Anti-Aging Medicine",
    folder: "Aesthetic & Anti-Aging Medicine",
    category: "healthcare",
    categoryLabel: "Healthcare & MedSpa",
    description: "Ultra-luxurious, medical-grade landing experience tailored for MedSpas, Botox clinics, anti-aging therapies, and cosmetic dermatology.",
    icon: "fa-notes-medical",
    badge: "High Conversion",
    gradient: "linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)",
    accentColor: "#ec4899",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80",
    tags: ["MedSpa", "Botox", "Dermatology", "Anti-Aging"],
    features: ["Online Booking CTA", "Before/After Gallery", "Doctor Profile", "Treatment Menu"]
  },
  {
    id: "dentist",
    title: "Modern Dental Clinic & Orthodontics",
    folder: "dentist",
    category: "healthcare",
    categoryLabel: "Healthcare & MedSpa",
    description: "Warm, trust-building dental practice website featuring online appointment scheduling, smile makeover galleries, and emergency care CTAs.",
    icon: "fa-tooth",
    badge: "Trust Standard",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)",
    accentColor: "#06b6d4",
    image: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=800&q=80",
    tags: ["Dentistry", "Teeth Whitening", "Orthodontist", "Smile Makeover"],
    features: ["Online Booking", "Smile Quiz", "Insurance Accepted", "Patient Reviews"]
  },
  {
    id: "dermatologist",
    title: "Dermatology & Skin Specialist",
    folder: "dermatologist",
    category: "healthcare",
    categoryLabel: "Healthcare & MedSpa",
    description: "Clinical yet approachable interface for clinical dermatologists, acne specialists, laser treatment clinics, and cosmetic skin doctors.",
    icon: "fa-user-md",
    badge: "Medical Grade",
    gradient: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    accentColor: "#10b981",
    image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=800&q=80",
    tags: ["Dermatology", "Skin Care", "Acne Treatment", "Laser Care"],
    features: ["Symptom Checker", "Doctor Credentials", "Treatment Guide", "Telehealth Link"]
  },
  {
    id: "doctor",
    title: "General Medical Practice & Doctor Clinic",
    folder: "doctor",
    category: "healthcare",
    categoryLabel: "Healthcare & MedSpa",
    description: "Clean, professional medical practice website built for primary care doctors, pediatricians, clinics, and family physicians.",
    icon: "fa-stethoscope",
    badge: "Essential",
    gradient: "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
    accentColor: "#0284c7",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80",
    tags: ["Primary Care", "Physician", "Family Doctor", "Clinic"],
    features: ["Patient Portal Link", "Specialty List", "Insurance Checker", "Emergency Info"]
  },

  // 7. Automotive & Detailing
  {
    id: "auto_detailing_ceramic_coating_shops",
    title: "Auto Detailing & Ceramic Coating",
    folder: "Auto Detailing & Ceramic Coating Shops",
    category: "automotive",
    categoryLabel: "Automotive & Detailing",
    description: "Sleek dark-themed template for auto detailing studios, paint protection film (PPF) specialists, ceramic coating, and custom vinyl wrap shops.",
    icon: "fa-car-side",
    badge: "Popular Niche",
    gradient: "linear-gradient(135deg, #00f2fe 0%, #4facfe 100%)",
    accentColor: "#00f2fe",
    image: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=800&q=80",
    tags: ["PPF & Vinyl", "Ceramic Coating", "Auto Wash", "Paint Correction"],
    features: ["Package Comparison", "Vehicle Selector", "360 Showcase", "Instant Quote Form"]
  },
  {
    id: "garage",
    title: "Auto Repair Garage & Service Center",
    folder: "garage",
    category: "automotive",
    categoryLabel: "Automotive & Detailing",
    description: "Trustworthy, conversion-oriented mechanic website for auto repair shops, brake services, engine diagnostics, and oil changes.",
    icon: "fa-wrench",
    badge: "Local Business",
    gradient: "linear-gradient(135deg, #64748b 0%, #334155 100%)",
    accentColor: "#64748b",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    tags: ["Auto Mechanic", "Engine Repair", "Brakes & Tires", "Oil Change"],
    features: ["Service Pricing", "Online Scheduling", "Tire Finder", "Customer Ratings"]
  },

  // 8. B2B & Commercial Services
  {
    id: "commercial_espresso_distributors",
    title: "Commercial Espresso Distributors",
    folder: "Commercial Espresso Machine Distributors",
    category: "services",
    categoryLabel: "B2B & Commercial Services",
    description: "Industrial, premium B2B catalog designed for commercial coffee equipment distributors, espresso machine repair, and roaster suppliers.",
    icon: "fa-mug-hot",
    badge: "B2B Focus",
    gradient: "linear-gradient(135deg, #d97706 0%, #92400e 100%)",
    accentColor: "#d97706",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    tags: ["B2B Equipment", "Espresso Machines", "Cafe Supplies", "Maintenance"],
    features: ["Equipment Spec Sheets", "Leasing Calculator", "Service Request", "Catalog PDF"]
  },
  {
    id: "artificial_turf_installation",
    title: "Artificial Turf & Landscaping",
    folder: "Artificial Turf Installation",
    category: "services",
    categoryLabel: "B2B & Commercial Services",
    description: "Clean, eco-green outdoor service template built for synthetic grass installers, putting greens, and residential turf solutions.",
    icon: "fa-seedling",
    badge: "High Growth",
    gradient: "linear-gradient(135deg, #22c55e 0%, #15803d 100%)",
    accentColor: "#22c55e",
    image: "https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80",
    tags: ["Synthetic Turf", "Golf Greens", "Pet Turf", "Landscape"],
    features: ["SqFt Estimator", "Texture Gallery", "Warranty Info", "Free Onsite Quote"]
  },
  {
    id: "roofing_contractors",
    title: "Roofing & Exterior Contractors",
    folder: "roofing contractors",
    category: "services",
    categoryLabel: "B2B & Commercial Services",
    description: "Heavy-duty lead generation template engineered for commercial & residential roofing, storm damage repair, and gutter contractors.",
    icon: "fa-house-chimney",
    badge: "High Conversion",
    gradient: "linear-gradient(135deg, #f97316 0%, #c2410c 100%)",
    accentColor: "#f97316",
    image: "https://images.unsplash.com/photo-1632759145351-1d592919f522?auto=format&fit=crop&w=800&q=80",
    tags: ["Roofing", "Storm Damage", "Gutters", "Commercial Repair"],
    features: ["Emergency Hotline CTA", "Inspection Request", "Insurance Claim Guide", "Project Map"]
  },
  {
    id: "city_portal",
    title: "Local City Directory & Business Portal",
    folder: "city portal",
    category: "services",
    categoryLabel: "B2B & Commercial Services",
    description: "Community directory and local business search portal designed for municipal hubs, local trade networks, and city guide listings.",
    icon: "fa-city",
    badge: "Portal Hub",
    gradient: "linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)",
    accentColor: "#6366f1",
    image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
    tags: ["City Directory", "Local Business", "Events Calendar", "Trade Listing"],
    features: ["Search Filter", "Claim Listing CTA", "Featured Spots", "Category Grid"]
  },
  {
    id: "vanguard_school_website",
    title: "Vanguard International School",
    folder: "vanguard-school-website",
    repoUrl: "https://github.com/pms5566/vanguard-school-website",
    category: "services",
    categoryLabel: "Education & Academy",
    description: "Modern, professional academy & school website built for Vanguard International School featuring interactive admissions, course guides, and campus tour.",
    icon: "fa-school",
    badge: "Academy",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)",
    accentColor: "#2563eb",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80",
    tags: ["School", "Education", "Admissions", "Campus Tour"],
    features: ["Course Guide", "Admissions Portal", "Campus Gallery", "Parent Portal"]
  },
  {
    id: "sarna_travels",
    title: "Sarna Travels & Premium Taxi Tours",
    folder: "sarna-travels",
    repoUrl: "https://github.com/pms5566/sarna-travels",
    category: "services",
    categoryLabel: "Travel & Transport",
    description: "Premium taxi, luxury car rental, and tour package booking service website featuring instant WhatsApp fare quotes and fleet showcase.",
    icon: "fa-route",
    badge: "Tour & Taxi",
    gradient: "linear-gradient(135deg, #eab308 0%, #ca8a04 100%)",
    accentColor: "#eab308",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    tags: ["Taxi Service", "Tour Packages", "Car Rental", "Outstation Taxi"],
    features: ["Instant Fare Quote", "Fleet Showcase", "WhatsApp Booking", "Route Estimator"]
  }
];
